# Generated by Django 6.0 on 2025-12-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etsy_listing_id", models.BigIntegerField(unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("url", models.URLField(blank=True)),
                ("price_amount", models.IntegerField(blank=True, null=True)),
                ("price_currency", models.CharField(blank=True, max_length=10)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("updated_at_etsy", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
