# Generated by Django 6.0 on 2026-01-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("etsy_buyer_user_id", models.BigIntegerField()),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "etsy_buyer_user_id"), name="uniq_owner_buyer_user_id"),
                ],
            },
        ),
    ]

