# Generated by Django 6.0 on 2025-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etsyaccount",
            name="shop_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etsyaccount",
            name="shop_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
