# Generated by Django 6.0 on 2025-12-19 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etsy_order_id", models.BigIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In transit"),
                            ("delivered", "Delivered"),
                            ("closed", "Closed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=255)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                ("total_amount", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("order_created_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etsy_listing_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("price_amount", models.IntegerField(blank=True, null=True)),
                ("price_currency", models.CharField(blank=True, max_length=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("carrier_name", models.CharField(blank=True, max_length=100)),
                ("carrier_status", models.CharField(blank=True, max_length=100)),
                ("carrier_status_raw", models.TextField(blank=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
