# Generated by Django 6.0 on 2025-12-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expected_ship_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
