# Generated by Django 6.0 on 2026-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_expected_ship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
